
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  type ContractNotes,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  L1EventPayload,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  NoteSelector,
  Point,
  type PublicKey,
  PublicKeys,
  type Wallet,
  type U128Like,
  type WrappedFieldLike,
} from '@aztec/aztec.js';
import BundlerContractArtifactJson from '../../../target/bundler-Bundler.json' with { type: 'json' };
export const BundlerContractArtifact = loadContractArtifact(BundlerContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract Bundler;
 */
export class BundlerContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, BundlerContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, BundlerContract.artifact, wallet) as Promise<BundlerContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<BundlerContract>(PublicKeys.default(), wallet, BundlerContractArtifact, BundlerContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<BundlerContract>(publicKeys, wallet, BundlerContractArtifact, BundlerContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof BundlerContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<BundlerContract['methods'][M]>
  ) {
    return new DeployMethod<BundlerContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      BundlerContractArtifact,
      BundlerContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return BundlerContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(BundlerContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'admin'> {
      return {
        admin: {
      slot: new Fr(1n),
    }
      } as ContractStorageLayout<'admin'>;
    }
    

  public static get notes(): ContractNotes<'UintNote' | 'ValueNote'> {
    return {
      UintNote: {
          id: new NoteSelector(1),
        },
ValueNote: {
          id: new NoteSelector(0),
        }
    } as ContractNotes<'UintNote' | 'ValueNote'>;
  }
  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** cancel_reward_authwit(inner_hash: field) */
    cancel_reward_authwit: ((inner_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** cancel_stable_authwit(inner_hash: field) */
    cancel_stable_authwit: ((inner_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(admin: struct) */
    constructor: ((admin: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** exchange_tokens_private(from: struct, stable: struct, reward: struct, stable_amount: integer, reward_amount: integer, nonce: field) */
    exchange_tokens_private: ((from: AztecAddressLike, stable: AztecAddressLike, reward: AztecAddressLike, stable_amount: (bigint | number), reward_amount: (bigint | number), nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** exchange_tokens_public(from: struct, stable_token: struct, reward_token: struct, stable_amount: integer, reward_amount: integer, nonce: field) */
    exchange_tokens_public: ((from: AztecAddressLike, stable_token: AztecAddressLike, reward_token: AztecAddressLike, stable_amount: (bigint | number), reward_amount: (bigint | number), nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_log(log_ciphertext: struct, tx_hash: field, unique_note_hashes_in_tx: struct, first_nullifier_in_tx: field, recipient: struct) */
    process_log: ((log_ciphertext: { storage: FieldLike[], len: (bigint | number) }, tx_hash: FieldLike, unique_note_hashes_in_tx: { storage: FieldLike[], len: (bigint | number) }, first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** send_tokens_private(to: struct, reward_token: struct, stable_token: struct, stable_amount: integer, reward_amount: integer) */
    send_tokens_private: ((to: AztecAddressLike, reward_token: AztecAddressLike, stable_token: AztecAddressLike, stable_amount: (bigint | number), reward_amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** send_tokens_public(to: struct, reward_token: struct, stable_token: struct, stable_amount: integer, reward_amount: integer) */
    send_tokens_public: ((to: AztecAddressLike, reward_token: AztecAddressLike, stable_token: AztecAddressLike, stable_amount: (bigint | number), reward_amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_notes() */
    sync_notes: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
