[package]
name = "bundler"
type = "contract"
authors = [""]

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.82.0", directory="noir-projects/aztec-nr/aztec" }
authwit = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.82.0", directory="noir-projects/aztec-nr/authwit"}
token = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.82.0", directory="noir-projects/noir-contracts/contracts/token_contract" }